# Generated by Django 4.0.3 on 2022-03-27 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appnomina', '0003_alter_cargo_descripcion_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cargo',
            options={'ordering': ['id'], 'verbose_name': 'Cargo', 'verbose_name_plural': 'Cargos'},
        ),
    ]
